site:
  title: VNM Simulation Documentation
  url: https://vnmsimulation.github.io/
  start_page: vnm-simulation::index.adoc
content:
  sources:
  - url: .
    branches: HEAD
    start_path: docs-src
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  dir: ./docs
