site:
  title: VNM Simulation Documentation
  url: https://vnmsimulation.github.io/
  start_page: devices::index.adoc
content:
  sources:
  - url: .
    branches: HEAD
    start_paths:
      - docs-src/devices
      - docs-src/softwares
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: ./docs
